[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
raise_contract = "DWeQB5bkbGG8VWQxQHjqijw5jnTyxxUe75j8W3fzAgyq"

[programs.testnet]
raise_contract = "DWeQB5bkbGG8VWQxQHjqijw5jnTyxxUe75j8W3fzAgyq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/home/wsl/.config/solana/id.json"

[test]
startup_wait = 40000
shutdown_wait = 2000
upgradeable = false

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.test.ts"
