[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
raise_contract = "DWeQB5bkbGG8VWQxQHjqijw5jnTyxxUe75j8W3fzAgyq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/soldev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
